# theme: jekyll-theme-cayman

# Site settings
title: Rex Blog
SEOTitle: 张鑫的博客 | Rex Blog
header-img: img/home-bg.png
email: rex6817@gmail.com
description: "存储开发 | Storage Engineer | Rex的个人博客呀"
keyword: "Rex, 存储, Rex Blog"
url: "https://coderex2522.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Storage Engineer"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    coderex2522


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  repo: coderex2522.github.io    #仓库名称
  owner: coderex2522    #github用户名
  admin: coderex2522
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Favorites
Favorites: [
  {
    title: "Tesla",
    href: "https://www.tesla.com/"
  }
]
